version: "3.7"
services:
  #Node Service
  app:
    build:
      context: .
    image: cilas/gatsby
    container_name: gatsby
    restart: always
    tty: true
    working_dir: /usr/src/app
    volumes:
      - ./app/:/usr/src/app
    ports:
      - 8000:8000
    networks:
      - gatsby_net
#Docker Network
networks:
  gatsby_net:
    driver: bridge